### ISSUE TITLE
PoorPocketsMcNewHold's contributions to block google

### ISSUE THREAD

**Issue by nickspaargaren** [nickspaargaren/pihole-google#24]
Hi @PoorPocketsMcNewHold ,

Maybe you already noticed; I'm the initial creator of https://github.com/nickspaargaren/pihole-google!

I'd like to thank you for your contributions to our repository. I am very happy with your effort and would like to send you some investment money in crypto valuta. You can choose, I'll try to convert some.

$50. Anything you like; bitcoin, ethereum, litecoin, whatever, you name it. BAT perhaps? https://brave.com/nic944 :)

Just send me the correct address and which valuta you'd like. Again, thank you.

Nick Spaargaren

_(No this isn't a scam, not aware how crypto works? Just download brd.com and find out, I have send you an email so you can reply your address there)_

**Comment by PoorPocketsMcNewHold** [comment]
Hi Nick, thanks hugely for this donation.
This actually happens at a time in which i've actually unlocked some free time (Well, Not exactly right NOW as i'm currently in vacation for a short couple of days), in which i want to dedicate myself more on the project i currently contribute on GitHub, especially this one due to the recent gain of attention that we've got recently.
I didn't had any current active crypto account at this time of writing, so i've followed your suggestion and created myself one at BRD. 
I suggest Ethereum should do, but feel free to contact me more about it, at my address : poorpocketsmcnewhold@pm.me 
Other than that, Here's my ethereum address : 0x4C9A86c0b24303fEC712A58EAd5AD610fe0f18C6

**Comment by nickspaargaren** [comment]
https://etherscan.io/tx/0xaaa9a30cba630c7a3e4f4241d77cd45e0a3072d887fa714efc50d348247c4c99

Here you go! Again, thank you!

**Comment by PoorPocketsMcNewHold** [comment]
Pretty obvious with the ether proof, but i've indeed received it. I also return the compliment, for the donation, but also the creation of this liste that I use every days.
