### ISSUE TITLE
Or am I completely crazy?

### ISSUE THREAD

**Issue by nickspaargaren** [nickspaargaren/pihole-google#8]
What do you guys think?
https://acquiredby.co/google-acquisitions

**Comment by PoorPocketsMcNewHold** [comment]
Well, while those could be also monitored, we don´t aim to blacklist the whole Alphabet group, but mostly, any Google services that are directly linked to their main services, and in which, they could gain from tracking.
But it´s true that they´ve might maybe use these services aswell for that purpose, but i doubt this would be efficient to block them, especially since some companies seems to not have been fully disclosed as being part of the Alphabet group.
